name: Deploy Vue → infobase.tojest.dev

on:
  push:
    branches: [ "main" ]     # zmień, jeśli inny branch
  workflow_dispatch:         # pozwala odpalić ręcznie z UI

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run remote deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          # Jeśli masz "forced command" w authorized_keys, poniższy script może być no-op:
          script: |
            bash /var/www/vue-app/deploy.sh
