name: Deploy Strapi → api.infobase.tojest.dev

on:
  push:
    branches: [ "production" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Strapi via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd /var/www/strapi
            git fetch --all
            git reset --hard origin/main     # zmień, jeśli inny branch
            npm ci || npm install
            npm run build
            pm2 restart strapi
